version: '3.8'

services:
  sqlserver1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver1
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./scripts/sqlserver1/init.sql:/docker-entrypoint-initdb.d/init.sql

  sqlserver2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2
    restart: always
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./scripts/sqlserver2/init.sql:/docker-entrypoint-initdb.d/init.sql

  sqlserver3:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver3
    restart: always
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./scripts/sqlserver3/init.sql:/docker-entrypoint-initdb.d/init.sql

