
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      

  app:
    build: .
    container_name: nestjs_app
    depends_on:
      - mssql
    ports:
      - "3000:3000"
    environment:
      DB_SERVER: mssql
      DB_USER: sa
      DB_PASSWORD: YourStrong!Passw0rd
      DB_NAME: db_app
    volumes:
      - .:/usr/src/app
    command: npm run start

volumes:
  mssql_data:
